[package]
name = "app"
version = "0.1.0"
publish = false
edition = "2021"
rust-version = "1.69"

[dependencies]
gen = { path = "../gen" }
common = { path = "../common" }
closure = "0.3"
const-oid = "0.9"
der = { version = "0.7", features = ["time"] }
derive_builder = "0.12"
ecdsa = { version = "0.16", features = ["signing"] }
ed25519-dalek = { version = "2.0.0", features = ["rand_core", "pem"] }
enum-iterator = "1.4"
elliptic-curve = "0.13"
k256 = { version = "0.13", features = ["pem"] }
nom = "7.1"
num_enum = "0.6"
p256 = { version = "0.13", features = ["ecdsa", "sha256"] }
p384 = "0.13"
parse-display = "0.8"
pkcs1 = "0.7"
pkcs8 = { version = "0.10", features = ["alloc", "pem"] }
rand = { version = "0.8"}
rsa = { version = "0.9", features = ["sha2"] }
sha2 = { version = "0.10", features = ["oid"] }
signature = "2.1"
spki = { version = "0.7", features = ["pem"] }
time = { version = "0.3", features = ["wasm-bindgen"] }
uuid = { version = "1.3", features = ["v4", "js"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlOptionElement", "HtmlSelectElement"] }
x509-cert = "0.2"
yew = { version = "0.20", features = ["csr"] }
